// Generated by gencpp from file ti_mmwave_rospkg/mmWaveCLIResponse.msg
// DO NOT EDIT!


#ifndef TI_MMWAVE_ROSPKG_MESSAGE_MMWAVECLIRESPONSE_H
#define TI_MMWAVE_ROSPKG_MESSAGE_MMWAVECLIRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ti_mmwave_rospkg
{
template <class ContainerAllocator>
struct mmWaveCLIResponse_
{
  typedef mmWaveCLIResponse_<ContainerAllocator> Type;

  mmWaveCLIResponse_()
    : resp()  {
    }
  mmWaveCLIResponse_(const ContainerAllocator& _alloc)
    : resp(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _resp_type;
  _resp_type resp;





  typedef boost::shared_ptr< ::ti_mmwave_rospkg::mmWaveCLIResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ti_mmwave_rospkg::mmWaveCLIResponse_<ContainerAllocator> const> ConstPtr;

}; // struct mmWaveCLIResponse_

typedef ::ti_mmwave_rospkg::mmWaveCLIResponse_<std::allocator<void> > mmWaveCLIResponse;

typedef boost::shared_ptr< ::ti_mmwave_rospkg::mmWaveCLIResponse > mmWaveCLIResponsePtr;
typedef boost::shared_ptr< ::ti_mmwave_rospkg::mmWaveCLIResponse const> mmWaveCLIResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ti_mmwave_rospkg::mmWaveCLIResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ti_mmwave_rospkg::mmWaveCLIResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace ti_mmwave_rospkg

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::ti_mmwave_rospkg::mmWaveCLIResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ti_mmwave_rospkg::mmWaveCLIResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ti_mmwave_rospkg::mmWaveCLIResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ti_mmwave_rospkg::mmWaveCLIResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ti_mmwave_rospkg::mmWaveCLIResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ti_mmwave_rospkg::mmWaveCLIResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ti_mmwave_rospkg::mmWaveCLIResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b791c1a4a4f0cee32b54dd1a73706a59";
  }

  static const char* value(const ::ti_mmwave_rospkg::mmWaveCLIResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb791c1a4a4f0cee3ULL;
  static const uint64_t static_value2 = 0x2b54dd1a73706a59ULL;
};

template<class ContainerAllocator>
struct DataType< ::ti_mmwave_rospkg::mmWaveCLIResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ti_mmwave_rospkg/mmWaveCLIResponse";
  }

  static const char* value(const ::ti_mmwave_rospkg::mmWaveCLIResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ti_mmwave_rospkg::mmWaveCLIResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string resp\n\
\n\
";
  }

  static const char* value(const ::ti_mmwave_rospkg::mmWaveCLIResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ti_mmwave_rospkg::mmWaveCLIResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.resp);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct mmWaveCLIResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ti_mmwave_rospkg::mmWaveCLIResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ti_mmwave_rospkg::mmWaveCLIResponse_<ContainerAllocator>& v)
  {
    s << indent << "resp: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.resp);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TI_MMWAVE_ROSPKG_MESSAGE_MMWAVECLIRESPONSE_H
